<a href="https://colab.research.google.com/github/chunyuan0221/AI_study/blob/master/Data_preprocess(ndarray%E8%AA%AA%E6%98%8E).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
files.upload()

Saving 1_1.tif to 1_1.tif
Saving 1_1_mask.tif to 1_1_mask.tif
Saving 1_2.tif to 1_2.tif
Saving 1_2_mask.tif to 1_2_mask.tif


{'1_1.tif': b'II*\x00\x04%\x03\x00\x80\x00\x0b\x85B\x8c\x14\xa6S(\x94\n%R\xc1p\xbab4DL\xa6C!\x8c\xc7\x142\x99\xa21\x131\x9a2i6\x1c\x0eg3\x91\xb4\xd6j\x94\x1a\x8dg\x03\x91\xd0\xect\x97\x1d\xa5\xe7C\xd1\xc0\xf0x;\x9d\x8ercI\xa4\xd6q<\x1b\xe8\x07\xe4\n\n\x8c\x82B!\xd1\x88\xe4r1\x1a\x87>\x9d\xcf\xc8T2\x1d\x10\x85@\xa1Qi4\xd2q:\x9c\xb0\'\xacI\xe4\xeay>\xa1Q)\x93\xe9\xb4\xc2Y \x8fH$\xd2\xe9\xcb:\x89D\x9fOX\x13\tT\x9aQ8\xa2T)\x94\x8a\x14\xd2]0\x97K\xa6\x94J\xd5Z\xa9R\xabV)T)\xdb*\x85F\xa6U+\x15+%\x8a\xc3\x18\xaa\xc7h1\xca\x85*\x8dD\xa1O\xeaS\xf5\xf4\xe5\xed\x1fFD\xa4)\x88\xc4Z.\xae\x82?\x9fwG\xb3\xc9\xe5\x08\x90M\xa7\x12\xe8\xc4\n\x05\x0c\x93\xb3\xe9\xb4\xea\x1eg7\x92\xa5R\xa7\xb0\xa9\x84\xee\xa1:\x92B"\xed\xe8\xe4:\x04\xfd\xba>\x9f\xeb(\x94^\xd1\x0c\x80?\x9f\x90\xc8\xd4f\xd2\x9d\xecD\xa1\xd0\xe8d*\x11\x0c\x831\x9c\xc0\x1f\xbf\xe7\xf7\xfc\xfe\x01\xe0@\x8e#\x8ec\xc0\xe4=\xc1\x10A\x02>\xb7\x83\xb0\xea9\x8e\x03zx6B\x83X\xd66\x8d\xc3|$5\x8d\x03<:1\x0b\xc2\xe8\xba/\x8c\x03\x08\xc2/\x8b\xd1LC\x15DB

In [1]:
ls

1_1_mask.tif  1_1.tif  1_2_mask.tif  1_2.tif  sample_data/


In [2]:
import numpy as np
from skimage.io import imread, imsave
import os
from keras.preprocessing.image import img_to_array, load_img

Using TensorFlow backend.


In [0]:
image_rows = 420
image_cols = 580

images = []
for i in os.listdir():
  split_num = len(i.split('.'))
  if split_num == 2:
    if i.split('.')[1] == 'tif':
      images.append(i)

total = np.int(len(images) / 2)

### 做Data preprocessing時遇到的問題
***
- np.ndarray(shape, dtype=float, buffer=None, offset=0) : 
  - shape: 用turple型式給定陣列大小。ex:建立一個$3\times480\times540$的陣列空間來放置3張$480\times540$大小的圖片，**則以此表示: (3, 480, 540)**。  
   **注意**: shape內填的值要為$int$型態，不可是$float$，ex: (3.0, 480.0, 540.0) 在3.7版的python這樣會報錯
  - dtype: 給定陣列的型態，預設為$float$。 
  - buffer: 要放到這個陣列的資料透過buffer可以直接放入，但buffer資料的shape和我們建立的array shape要一致。
  - offset: 透過offset可修改buffer內的資料。
  - 小結: 
    1. 透過ndarray已經先宣告array的大小，因此我們可以直接給值。  
     ex: 我們手邊有3張圖片，我們想將這3張圖片合併在1個array中。用np.ndarray建立好一個A，A.shape = (3, 480, 540)，接著依序將圖片放入A中。
            A = np.ndarray((3, 480, 540), dtype=np.uint8)
            print(A.shape)    # A.shape=(3, 480, 540)
            for i in images:  # images代表三張圖片
              A[0] = i
      
    2. 在這邊我很好奇，ndarray建立出來後裡面的數值長怎樣? 若我們給的dtype=int 內部的數值皆為0；若dtype=float 內部的結果有0、有逼近0的小數、有None。
    3. 因此，你也可用 np.zeros(shape, dtype) 來表示，思維上更簡單多。



In [4]:
# 示範buffer
a = np.arange(0, 480*540, 1)
a = a.reshape((-1, 480, 540))
print(a.shape)
imgs = np.ndarray((1, image_rows, image_cols), buffer=a)

(1, 480, 540)


In [5]:
imgs = np.ndarray((total, image_rows, image_cols), dtype=np.uint8)
imgs_mask = np.ndarray((total, image_rows, image_cols), dtype=np.uint8)
print(imgs.shape)
imgs[0]

(2, 420, 580)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [6]:
imgs1 = np.zeros((total, image_rows, image_cols), dtype=np.uint8)
print(imgs1.shape)
imgs1[0]

(2, 420, 580)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [0]:
i = 0
for image_name in images:    # 因為檔案名稱的差別只有"_mask"，沒有"_mask"是input data，有"_mask"的是output data(label)
  if 'mask' in image_name:   # 為了讓每次迴圈能同時處理同1組資料，以這樣表示
    continue
  image_mask_name = image_name.split('.')[0] + '_mask.tif'
  img = imread(image_name, as_gray=True)
  img_mask = imread(image_mask_name, as_gray=True)

  # 原始資料的shape=(480, 540)，需增加1個維度=>(1, 480, 540)後面才能放入
  img = np.array([img])
  img_mask = np.array([img_mask])

  # 放資料
  imgs[i] = img
  imgs_mask[i] = img_mask
  i += 1

In [8]:
# 看結果，沒問題。後續可儲存.npy檔
print(imgs.shape)
imgs[0]

(2, 420, 580)


array([[  0,  30,  40, ..., 108, 111, 109],
       [  0, 101,  79, ..., 161, 162, 159],
       [  0, 167, 137, ..., 165, 165, 163],
       ...,
       [  0,  58,  45, ...,  23,  22,  22],
       [  0,  59,  48, ...,  20,  19,  19],
       [  0,  98,  82, ...,  15,  13,  13]], dtype=uint8)